# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: asia.gcr.io/mclinica-analytics/data-analytics-swiperx-dbt-docs
  tag: latest
  pullPolicy: IfNotPresent

env:

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 1
    memory: 2000Mi
  requests:
    cpu: 100m
    memory: 100Mi