parameters:
- name: envCode
  type: string
- name: projectPrefix
  type: string
- name: gcrConnName
  type: string
- name: gcrRepoName
  type: string

jobs:
  - deployment: Deploy
    variables:
    - group: '${{ parameters.projectPrefix }}-${{ parameters.envCode }}'
    displayName: '${{ parameters.envCode }} deployment'
    environment: '${{ parameters.projectPrefix }}-${{ parameters.envCode }}'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Docker@2
            displayName: "Login to Docker"
            inputs:
              command: 'login'
              containerRegistry: '${{ parameters.gcrConnName }}'

          - script: |
              docker run 'asia.gcr.io/${{ parameters.gcrRepoName }}' seed --vars '$(DBT_VARS)'
            displayName: "Deploy DBT Seeds"

          - script: |
              docker run 'asia.gcr.io/${{ parameters.gcrRepoName }}' run --vars '$(DBT_VARS)'
            displayName: "Deploy DBT Run"

          - script: |
              docker run 'asia.gcr.io/${{ parameters.gcrRepoName }}' test --vars '$(DBT_VARS)'
            displayName: "DBT Test"



